apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: argocd
spec:
  encryptedData:
    ROOT_PASSWORD: AgCb5SfCtwCHdjnYnh9Ih9e2bkSX/HhRE945N/ZzR6J5R26kwUr4xryQijB/4wg7yqrzHZK80sqot9PKX6xDOftaXx6OSo+eIsfJEG3/P5oV3Ki8WlAjNqjU+Q4+Rxt3DeetYTIGlI/C2XPZxssZ31ZbxtEqOkWu+mVLnUraADXr7kACfHpMvP6WAJKvroMrmPw9MfbMGWN+srzossLZNPajreU59Yp2Aj7Flspyx7wKg+RhRa69W+O5k3LE/r1CDkRyMMECMx3fUn5/hYKlQ8MrFK+1o7oQ9KXlFqfGYcWnPobsVRL4fRkOKY0dTJLxNkMUKrJ9HB3dLyaNU54sIa4QR6KSFy5IPtCa//6Zn1N709m66pgFMrdhG9z00ouEv34Sc5tiVkN57tdgsmi1xRZRxQxJo7+LjL4kjnqxo3sFp8ONh/hsZlmYVt2hG8pVBrGRrlZZt0HDNpHSyr2zDfYGnOzEkvzlodxT2WBdopWniAdOkkiJ4OKcfTJnIKoeaFAZ30840c6aKYC8nkvDV5pjxlnHK6MKpT5055aeIPbb59l7PJLtaChTudUuVW7KCxjFSoQOOBNK612JYBHu2t3NO7iC3Aw2U3tCcd0V8FO9Y7aj0hN68QCpLVUnve+cnlFCH+F7J4BpTDiFcxkSfqBQrKsgWWcbfPVmoGYH81RvoJ4wTZ/RsnLT1QxAvBnMANukijzXTFfhIEFImgnajKT+xW0=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: argocd

