apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
     job: node-api
     app: api
spec:
  selector:
    app: api
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    protocol: TCP
