apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage
  resources:
    requests:
      storage: 500Mi
