apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
    - image: fedora:26
      name: fc-container
      command: [ "/bin/sh", "-c" ]
      args: [ "tail -f /dev/null" ]
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: some-claim