apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: dev
spec:
  type: NodePort

  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080