apiVersion: v1
kind: Service
metadata:
  name: metrics-app-service
  labels:
     job:  go-metrics-app
     app: metrics-service
spec:
  type: ClusterIP
  selector:
    app: metrics-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
