apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-app-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: web-ip
    networking.gke.io/managed-certificates: ops-apps-ingress-cert
    networking.gke.io/v1beta1.FrontendConfig: "ops-apps-frontend-config"
spec:
  rules:
    - host: ops.infotitans.se
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ops-app-service
                port:
                  number: 8080

---

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ops-apps-ingress-cert
spec:
  domains:
    - ops.infotitans.se

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ops-apps-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT