apiVersion: v1
kind: Service
metadata:
  name: ops-app-service
  labels:
     job: ops-app-service
     app: ops-app
spec:
  type: ClusterIP
  selector:
    app: ops-app
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80