apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-app-deployment
  labels:
    app: ops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ops-app
  template:
    metadata:
      labels:
        app: ops-app
    spec:
      containers:
        - name: ops-app
          image: profemzy/ops-app:v1
          command:
            - "tail"
            - "-f"
            - "/dev/null"
          ports:
            - containerPort: 80
