apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    ROOT_PASSWORD: AgAEzuTNKvMXJZJ+5TkUk2MotBa11eL8MFNbJE8R0Zz9LLhNj32nlWWfCTQnKd973plXIFQnitViZADovYi1rf4gSRS2gWFTqnHxFy+k5SUFMp/bQN8Ubasmt6Mv9owPZ0kPDLYGu8A8z92ajNVXBZYAMOWj3M5/OndU9T6UYdu7llTYdyeF9Jsp/7vxkAH8ZdpULbvhCGsQEl1JYtKwc7mURJflO0I3E1o/5m+XGC5HPxHJnwzkHmG4Xa6epLsdDiHiObtouhpYc+F2rQ4rgpHjEwjKCAghilVyXMqcEyOY0Q+6iX4NvALjAFmcZrYJe49XAkC4wfIZo9tzrl7PR5/lX8jbMMomlSGgsbfUq5PmDzYJiFMipq3S+n4GLvBKxv2rxBDrnHoJlkuOB3K8/ZI4PC/FOImE/N3UPgAr8Zxu52e6Q1GYsXxs7Z/qEZKpkjFsp0nG/8ujpsp8BM8stbzIFVDmGjReUvl/BjQZ4gBsHKNIbLkLwUiXXvyka864aV8wDoV3pmo7AT3pXQDBNDo+85s+tNC3iBcKymRiE4YteZ9aHw8oelRdESANPx/pCpTKlUskBjPBfNBBDTA+I4OfAcIW7dVS5W6K++XXktakyO0MkhRwnc1z3k3ZYAimKU2iq4tYjGdUMLYfZ+R/lmDSHLiBaf2UNClR7Vr+gIcAORxeG+AOfRtTI4wZPyzl2C3d8b/fLG77Guiyd3f+Oot2rVvQ3aXqAYP/LaGyKWUg8xMBnsYOhkJXpn6M
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default

